name: Compilar GBA

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar devkitPro
        uses: devkitPro/actions/install@main

      - name: Instalar Butano y Tonc
        run: |
          dkp-pacman -Syu --noconfirm tonclib butano

      - name: Compilar juego
        run: |
          make

      - name: Guardar archivo ROM (.gba)
        uses: actions/upload-artifact@v4
        with:
          name: juego-gba
          path: |
            *.gba
            out/*.gba
